<?php
// Displays admin menu page
function milo_browser_display_settings() {
  global $milo_adminSettings;
  global $milo_pluginSlug;
  ?>
  <form id="plugin-settings" method="post" action="options.php">

    <?php
    // Outputs nonce, action and option_page fields
    settings_fields( $milo_pluginSlug );
    do_settings_sections( $milo_pluginSlug );
    ?>

    <style>
      .separator{
        border-bottom: 1px solid black;
      }
    </style>

    <div>
      <h1>
        MILO Range - S3 Browser Settings
      </h1>
      <p>
        Please set your AWS access key and secret below, along with the region that your target bucket(s) reside in. Make sure you have the proper IAM permissions or your data will not display! The simplest way to show a bucket is with a shortcode, with the following format: <code>[milos3browser bucket=s3-bucket-name]</code>
      </p>
      <p>
        Any user with administrator privileges can automatically view the browser pages, but they will be behind a password for everyone else. This is auto-generated by the server and posted below.
      </p>
      <p>
        Huge thanks to Dan Dulaney aka <a href="https://github.com/duplaja" target="_blank">duplaja</a> for making his S3 bucket browser plugin open for public scrutiny. This plugin would not exist without it.
      </p>

      <table class="form-table">
        <tr>
          <td colspan="3">
            <h2>
              Amazon S3 Settings
            </h2>
          </td>
        </tr>
        <tr valign="top">
          <th scope="row">
            AWS Access Key
          </th>
          <td>
            <input type="text" name="aws_key" value="<?php echo esc_attr( get_option('aws_key') ); ?>" />
          </td>
          <td>
            <p>
              Enter your AWS access key here.
            </p>
          </td>
        </tr>
        <tr valign="top">
          <th scope="row">
            AWS Secret
          </th>
          <td>
            <input type="text" name="aws_secret" value="<?php echo esc_attr( get_option('aws_secret') ); ?>" />
          </td>
          <td>
            <p>
              Enter your account secret here - it's only shown when the account is created, so if you don't have it you may need to ask for another one to be created for you
            </p>
          </td>
        </tr>
        <tr>
          <th scope="row">
            AWS Region
          </th>
          <td>
            <input type="text" name="aws_region" value="<?php echo esc_attr( get_option('aws_region') ); ?>" />
          </td>
          <td>
            <p>
              The region your bucket(s) reside in. Probably <code>us-east-1</code>
            </p>
          </td>
        </tr>
        <tr>
          <td colspan="3">
            <h2>
              Content Protection Settings
            </h2>
          </td>
        </tr>
        <tr valign="top">
          <th scope="row">
            Auto-Generated Password
          </th>
          <td>
            <code>
              <?php
                if(
                  ! get_option( 'milo_generated_key' ) ||
                  strlen( get_option( 'milo_generated_key' ) ) < 1
                ):
                  milo_password_generator();
                endif;
                echo esc_attr( get_option('milo_generated_key') );
              ?>
            </code>
            <input type="hidden" name="milo_generated_key" value="<?php echo esc_attr( get_option( 'milo_generated_key' ) ); ?>" />
          </td>
          <td>
            <p>
              This password can also be used for accessing content and can be shared for short-term purposes. It is automatically regenerated every month.
            </p>
          </td>
        </tr>
        <tr class="separator">
          <th scope="row">
            Email Address(es)
          </th>
          <td>
            <textarea name="email_addresses" form="plugin-settings"
              autocapitalize="none" autocomplete="on"
              cols="48" rows="3" style="resize:none;"
              placeholder="email@website.com"
              ><?php if( get_option( 'email_addresses' ) != ''):echo esc_attr( get_option('email_addresses') ); else: echo 'Comma-separated email addresses'; endif; ?></textarea>
          </td>
          <td>
            <p>
              Email addresses to update when the password regenerates. Multiple addresses should be separated by commas.
            </p>
          </td>
        </tr>
      </table>
    </div>

    <?php submit_button(); ?>
  </form>
  <?php
}
