#!/bin/sh

# JS documentation generator
# Tool for "Kocuj Sitemap plugin"

# Author: Dominik Kocuj
# License: http://www.gnu.org/licenses/gpl-2.0.html (GNU General Public License v2 or later)
# Copyright (c) 2013-2018 kocuj.pl

# Requires: "jsdoc" script


# WARNING! This tool is only for developers of this product. If you are not a developer, please, do not execute this file.


jsdoc -d="doc/js" -a -r -p -E="\.min\.js" -E="tools\/" -v ../
