#!/bin/sh

# JS minify
# Tool for "Kocuj.pl Lib"

# Author: Dominik Kocuj
# License: http://www.gnu.org/licenses/gpl-2.0.html (GNU General Public License v2 or later)
# Copyright (c) 2016-2018 kocuj.pl

# Requires: "uglifyjs" script for "node.js"


# WARNING! This tool is only for developers of this product. If you are not a developer, please, do not execute this file.


uglifyjs -o "../js/exception.min.js" "../js/exception.js" -c
uglifyjs -o "../js/exception-code.min.js" "../js/exception-code.js" -c
if [ -f "../js/project/components/backend/add-thanks/add-thanks.js" ]; then
    uglifyjs -o "../js/project/components/backend/add-thanks/add-thanks.min.js" "../js/project/components/backend/add-thanks/add-thanks.js" -c
fi
